Actions toolchain version increment

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -25,20 +25,20 @@ jobs:
         if: startsWith(github.ref_name, 'v')
         runs-on: ubuntu-latest
         steps:
-            - name: Checkout
-              uses: actions/checkout@v4
-              with:
-                  fetch-depth: 0
+            -   name: Checkout
+                uses: actions/checkout@v4
+                with:
+                    fetch-depth: 0
 
-            - name: Git tag is Semantic Versioning
-              env:
-                  DIS_RS_REF_NAME: ${{ github.ref_name }}
-              run: |
-                  _tag="$DIS_RS_REF_NAME"
-                  if ! printf "%s\n" "$_tag" | grep -q -P '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(alpha|beta|rc)\.(0|[1-9][0-9]*))?$'; then
-                    printf '[ERROR]: Git tag (%s) wrong format\n' "$_tag"
-                    exit 1
-                  fi
+            -   name: Git tag is Semantic Versioning
+                env:
+                    DIS_RS_REF_NAME: ${{ github.ref_name }}
+                run: |
+                    _tag="$DIS_RS_REF_NAME"
+                    if ! printf "%s\n" "$_tag" | grep -q -P '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(alpha|beta|rc)\.(0|[1-9][0-9]*))?$'; then
+                      printf '[ERROR]: Git tag (%s) wrong format\n' "$_tag"
+                      exit 1
+                    fi
 
     check:
         name: Build & Format & Lint & Test & Coverage
@@ -52,55 +52,55 @@ jobs:
                     - ubuntu-latest
                     - windows-latest
                 toolchain:
-                    - "1.74"
+                    - "1.76"
                     - stable
                 profile:
                     - dev
                     - release
         runs-on: ${{ matrix.os }}
         steps:
-            - name: Checkout
-              uses: actions/checkout@v4
-              with:
-                  fetch-depth: 0
+            -   name: Checkout
+                uses: actions/checkout@v4
+                with:
+                    fetch-depth: 0
 
-            - name: Setup Rust
-              uses: dtolnay/rust-toolchain@master
-              with:
-                  toolchain: ${{ matrix.toolchain }}
-                  components: clippy, rustfmt
-            
-            - name: Setup Tarpaulin
-              if: matrix.toolchain == 'stable'
-              run: cargo install cargo-tarpaulin
+            -   name: Setup Rust
+                uses: dtolnay/rust-toolchain@master
+                with:
+                    toolchain: ${{ matrix.toolchain }}
+                    components: clippy, rustfmt
 
-            - name: Setup Bun
-              uses: oven-sh/setup-bun@v2
-              with:
-                  bun-version: latest
+            -   name: Setup Tarpaulin
+                if: matrix.toolchain == 'stable'
+                run: cargo install cargo-tarpaulin
 
-            - name: Install Bun dependencies
-              working-directory: ./cdis-gateway
-              run: bun install
+            -   name: Setup Bun
+                uses: oven-sh/setup-bun@v2
+                with:
+                    bun-version: latest
 
-            - name: Build
-              run: cargo build --profile ${{ matrix.profile }} --verbose --all-features --all-targets --workspace
+            -   name: Install Bun dependencies
+                working-directory: ./cdis-gateway
+                run: bun install
 
-            - name: Format
-              run: cargo fmt --verbose --check --all
+            -   name: Build
+                run: cargo build --profile ${{ matrix.profile }} --verbose --all-features --all-targets --workspace
 
-            - name: Lint
-              run: cargo clippy --profile ${{ matrix.profile }} --verbose --all-features --all-targets --all
+            -   name: Format
+                run: cargo fmt --verbose --check --all
 
-            - name: Test
-              run: cargo test --profile ${{ matrix.profile }} --verbose --all-features --all-targets --workspace
+            -   name: Lint
+                run: cargo clippy --profile ${{ matrix.profile }} --verbose --all-features --all-targets --all
 
-            - name: Coverage
-              if: matrix.toolchain == 'stable'
-              run: cargo tarpaulin --profile ${{ matrix.profile }} --verbose --all-features --all-targets --workspace --out xml
+            -   name: Test
+                run: cargo test --profile ${{ matrix.profile }} --verbose --all-features --all-targets --workspace
 
-            - name: Upload coverage
-              if: matrix.toolchain == 'stable'
-              uses: codecov/codecov-action@v5
-              with:
-                token: ${{ secrets.CODECOV_TOKEN }}
+            -   name: Coverage
+                if: matrix.toolchain == 'stable'
+                run: cargo tarpaulin --profile ${{ matrix.profile }} --verbose --all-features --all-targets --workspace --out xml
+
+            -   name: Upload coverage
+                if: matrix.toolchain == 'stable'
+                uses: codecov/codecov-action@v5
+                with:
+                    token: ${{ secrets.CODECOV_TOKEN }}
